# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de2d4e76dd66a58513763eef1e329615fccb116a717ef6d6680e5e77878da2369cb241f5aa15b8d90ba80ef444df3ba0beda1990c7376198f478b9f443941806

test:
  secret_key_base: 7b6dbfbf2a9c3a3569a18775a49d41558b1eb652b04fd817666051d7189d3731a8a330f8032b74f0e4fbd9f62155b55f28df30e798642bfc5da117a8f54aef80

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
